version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
    - "39901:9000"
    volumes:
    - /data/docker/portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock

