version: '2.0'
services:
  mysql:
    # 基础镜像
    image: mysql:latest
    #容器名称
    container_name: mysql
    # 开机启动，失败也会一直重启
    restart: always
    # 端口
    ports:
      - "23306:3306"
    environment:
    # 密码设置
      - MYSQL_ROOT_PASSWORD=xDDeE53JNXK@V#
      - MYSQL_LOG_CONSOLE=true
    # 持久化数据挂载
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs

  redis:
    image: redis:latest
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - 26379:6379
    command: ["redis-server","/etc/redis/redis.conf"]
    restart: always
    volumes:
      - ./redis/conf:/etc/redis/
      - ./redis/data:/data
      - 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=xDDeE53JNXK@V#
    volumes:
      - ./mongodb/data:/data/db
